name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Install .NET dependencies
      id: install_dotnet_dependencies
      shell: powershell
      run: dotnet tool restore

    - name: Build project
      id: build_project
      shell: powershell
      run: dotnet fake run Source\Builder\build.fsx target ci
      env:
        FORCE_VERSION: ${{ steps.tag_generator.outputs.new_version }}
