name: Bogus CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    runs-on: windows-latest
    outputs:
      new_version: ${{ steps.tag_generator.outputs.new_version }} 
    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
         java-version: 1.11

      - name: Clean .NET cache
        id: clean_dotnet_cache
        shell: powershell
        run: |
          dotnet clean ./Source/Bogus.sln --configuration Release 
          dotnet nuget locals all --clear

      - name: Install .NET dependencies
        id: install_dotnet_dependencies
        shell: powershell
        run: dotnet tool restore

      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Bump release version and create release tag
        id: tag_generator
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false


      - if: github.event_name == 'push'
        name: Lowercase string generator
        id: lowercase_string_gen
        shell: powershell
        run: |
          $LOWERCASE_OWNER = "${{ github.repository_owner }}".ToLower()
          echo "::set-output name=owner_name::$LOWERCASE_OWNER"

      - name: Build project
        id: build_project
        shell: powershell
        run: dotnet fake run Source\Builder\build.fsx target ci
        env:
          FORCE_VERSION: ${{ steps.tag_generator.outputs.new_version }}
      - name: npm install, make test-coverage
        run: |
          npm install
          make test-coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
